name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Check Django
        run: |
          cd backend
          pip install -r requirements.txt
          python manage.py check

      - name: Build Docker images
        run: docker compose build
